import { NextPage } from 'next'
import Head from 'next/head'
import { useCallback } from 'react'
import { RootState } from '../app/store'
import { useAppDispatch, useAppSelector } from '../app/store'
import { increment, decrement, setValue } from '../features/counterSlice';
import { NumberInput, Group, ActionIcon, Divider, NativeSelect } from '@mantine/core';
import { IconChevronDown } from '@tabler/icons'
import { setText } from '../features/inputSlice'

const data = [
  { value: "", label: "Select an option", disabled: true },
  { value: "Option 1", label: "Option 1" },
  { value: "Option 2", label: "Option 2" },
];
const Home: NextPage = () => {
  const dispatch = useAppDispatch();
  const { val } = useAppSelector((state: RootState) => state.counter);
  const { text } = useAppSelector((state: RootState) => state.selectText)
  const onIncrement = useCallback(() => dispatch(increment()), [])
  const onDecrement = useCallback(() => dispatch(decrement()), [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <span>{val}</span>
        <Group spacing={5}>
          <ActionIcon size={42} variant="default" onClick={onDecrement}>
            –
          </ActionIcon>
          <NumberInput
            hideControls
            value={val}
            onChange={val => dispatch(setValue(val))}
            max={10}
            min={0}
            step={2}
            styles={{ input: { width: 54, textAlign: 'center' } }}
          />
          <ActionIcon size={42} variant="default" onClick={onIncrement}>
            +
          </ActionIcon>
        </Group>
        <Divider my="sm" />
        <NativeSelect
          value={text}
          rightSection={<IconChevronDown size={14} />}
          rightSectionWidth={30}
          onChange={(event) => dispatch(setText(event.currentTarget.value))}
          data={data}
        />
      </>
    </>
  )
}
export default Home